// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: test_service.proto

#include "test_service.pb.h"
#include "test_service.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace test {
namespace app {

static const char* TestService_method_names[] = {
  "/test.app.TestService/ProcessTick",
};

std::unique_ptr< TestService::Stub> TestService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< TestService::Stub> stub(new TestService::Stub(channel, options));
  return stub;
}

TestService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_ProcessTick_(TestService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  {}

::grpc::ClientReaderWriter< ::test::app::OrderResponse, ::test::app::OrderRequest>* TestService::Stub::ProcessTickRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::test::app::OrderResponse, ::test::app::OrderRequest>::Create(channel_.get(), rpcmethod_ProcessTick_, context);
}

void TestService::Stub::async::ProcessTick(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::test::app::OrderResponse,::test::app::OrderRequest>* reactor) {
  ::grpc::internal::ClientCallbackReaderWriterFactory< ::test::app::OrderResponse,::test::app::OrderRequest>::Create(stub_->channel_.get(), stub_->rpcmethod_ProcessTick_, context, reactor);
}

::grpc::ClientAsyncReaderWriter< ::test::app::OrderResponse, ::test::app::OrderRequest>* TestService::Stub::AsyncProcessTickRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::test::app::OrderResponse, ::test::app::OrderRequest>::Create(channel_.get(), cq, rpcmethod_ProcessTick_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::test::app::OrderResponse, ::test::app::OrderRequest>* TestService::Stub::PrepareAsyncProcessTickRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::test::app::OrderResponse, ::test::app::OrderRequest>::Create(channel_.get(), cq, rpcmethod_ProcessTick_, context, false, nullptr);
}

TestService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TestService_method_names[0],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< TestService::Service, ::test::app::OrderResponse, ::test::app::OrderRequest>(
          [](TestService::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReaderWriter<::test::app::OrderRequest,
             ::test::app::OrderResponse>* stream) {
               return service->ProcessTick(ctx, stream);
             }, this)));
}

TestService::Service::~Service() {
}

::grpc::Status TestService::Service::ProcessTick(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::test::app::OrderRequest, ::test::app::OrderResponse>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace test
}  // namespace app

